### ISSUE TITLE
Filter for ETH ticker missing in Step 3 - Daily Prices Question 6

### ISSUE THREAD

**Issue by anikait1** [DataWithDanny/sql-masterclass#2]
> What is the monthly average of the price column for Ethereum in 2020? Sort the output in chronological order and also round the average price value to 2 decimal places

[Question 6](https://github.com/DataWithDanny/sql-masterclass/blob/main/course-content/step3.md#question-6) asks to calculate monthly average price for Ethereum in 2020, however the solution is missing a where clause for the same.

**Current Solution**
```sql
SELECT
  DATE_TRUNC('MON', market_date) AS month_start,
  -- need to cast approx. floats to exact numeric types for round!
  ROUND(AVG(price)::NUMERIC, 2) AS average_eth_price
FROM trading.prices
WHERE EXTRACT(YEAR FROM market_date) = 2020
GROUP BY month_start
ORDER BY month_start;
```

**Correct Solution**
```sql
SELECT
  DATE_TRUNC('MON', market_date) AS month_start,
  -- need to cast approx. floats to exact numeric types for round!
  ROUND(AVG(price)::NUMERIC, 2) AS average_eth_price
FROM trading.prices
WHERE EXTRACT(YEAR FROM market_date) = 2020 AND ticker = 'ETH'
GROUP BY month_start
ORDER BY month_start;
```

**Comment by DataWithDanny** [comment]
I've updated this now - thanks for letting me know and sorry for the delay!
