### ISSUE TITLE
Step 4 Question 3 wrong answer

### ISSUE THREAD

**Issue by artik00** [DataWithDanny/sql-masterclass#5]
The question is For each year, calculate the following buy and sell metrics for Bitcoin:

The SQL answer is :
SELECT
  EXTRACT(YEAR FROM txn_date) AS txn_year,
  txn_type,
  COUNT(*) AS transaction_count,
  ROUND(SUM(quantity)::NUMERIC, 2) AS total_quantity,
  ROUND(AVG(quantity)::NUMERIC, 2) AS average_quantity
FROM trading.transactions
GROUP BY txn_year, txn_type
ORDER BY txn_year, txn_type;

Missing Where ticker='BTC'

The answer table is wrong as well.

**Comment by datawithdanny** [comment]
Fixed both of these now in #19 and #20 - thanks for the help :)
